### ISSUE TITLE
Exercise 9: Not able to run app from VSCode codespaces

### ISSUE THREAD

**Issue by lavkarbo** [equinor/appsec-fundamentals-authn-authz-cs#22]
I was not able to run the app in GitHub Codespaces from the Remote explorer in Visual Studio Code. Possibly also not working in ex 10 and 11 either.

**Comment by larskaare** [comment]
Could you please elaborate a bit more? What is "remote explorer" and what error messages did you get (in the front-end / back-end)

**Comment by lavkarbo** [comment]
Remote explorer in vscode is the pane shown below:
![image](https://github.com/equinor/appsec-fundamentals-authn-authz-cs/assets/104062801/3f82c455-7807-4051-97a4-de31c1cf81dd)
Here it shows the connected code space "bug-free lamp".

I am currently not able to reproduce the issue, so closing the issue.
